 -- Criar e selecionar o banco
 CREATE DATABASE IF NOT EXISTS DBCONDOMINIO
 CHARACTER SET utf8mb4
 COLLATE utf8mb4_unicode_ci;

 USE DBCONDOMINIO;
 
 CREATE TABLE PESSOAS (
 ID_PESSOA INT AUTO_INCREMENT PRIMARY KEY,
 NOME VARCHAR(150) NOT NULL,
 TIPO_PESSOA ENUM('FISICA','JURIDICA') NOT NULL,
 CPF_CNPJ VARCHAR(20) NOT NULL UNIQUE,
 DATA_CADASTRO DATE NOT NULL
 );
 
 CREATE TABLE CONTATOS (
 ID_CONTATO INT AUTO_INCREMENT PRIMARY KEY,
 ID_PESSOA INT NOT NULL,
 TIPO_CONTATO ENUM('TELEFONE','EMAIL','WHATSAPP') NOT NULL,
 VALOR_CONTATO VARCHAR(100) NOT NULL,
 FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS(ID_PESSOA)
 ON DELETE CASCADE
 );

 CREATE TABLE ENDERECOS (
 ID_ENDERECO INT AUTO_INCREMENT PRIMARY KEY,
 ID_PESSOA INT NOT NULL,
 LOGRADOURO VARCHAR(150),
 NUMERO VARCHAR(10),
 BAIRRO VARCHAR(100),
 CIDADE VARCHAR(100),
 UF CHAR(2),
 CEP VARCHAR(9),
 FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS(ID_PESSOA)
 ON DELETE CASCADE
 );
 
 CREATE TABLE UNIDADES (
 ID_UNIDADE INT AUTO_INCREMENT PRIMARY KEY,
 NUM_UNIDADE VARCHAR(10) NOT NULL,
 BLOCO VARCHAR(10) NOT NULL,
 TIPO VARCHAR(20),
 AREA_TOTAL DECIMAL(10,2)
 );

 CREATE TABLE MORADORES (
 ID_MORADOR INT AUTO_INCREMENT PRIMARY KEY,
 ID_PESSOA INT NOT NULL,
 ID_UNIDADE INT NOT NULL,
 FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS(ID_PESSOA),
 FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADES(ID_UNIDADE)
 );

 CREATE TABLE FUNCIONARIOS (
 ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
 ID_PESSOA INT NOT NULL,
 FUNCAO VARCHAR(50),
 DATA_ADMISSAO DATE,
 SALARIO DECIMAL(10,2),
 FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS(ID_PESSOA)
 );

 CREATE TABLE FORNECEDORES (
 ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
 ID_PESSOA INT NOT NULL,
 AREA_ATUACAO VARCHAR(100),
 FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS(ID_PESSOA)
 );

 CREATE TABLE VISITANTES (
 ID_VISITANTE INT AUTO_INCREMENT PRIMARY KEY,
 ID_PESSOA INT NOT NULL,
 DOCUMENTO VARCHAR(20),
 FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS(ID_PESSOA)
 );
 
 CREATE TABLE AREAS_COMUNS (
 ID_AREA_COMUM INT AUTO_INCREMENT PRIMARY KEY,
 NOME_AREA VARCHAR(50) NOT NULL,
 DESCR_AREA TEXT,
 CAPACIDADE INT
 );

 CREATE TABLE RESERVAS (
 ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
 ID_AREA_COMUM INT NOT NULL,
 ID_MORADOR INT NOT NULL,
 DATA_RESERVA DATE NOT NULL,
 HR_INICIO TIME,
 HR_FIM TIME,
 FOREIGN KEY (ID_AREA_COMUM) REFERENCES AREAS_COMUNS(ID_AREA_COMUM),
 FOREIGN KEY (ID_MORADOR) REFERENCES MORADORES(ID_MORADOR)
 );

 CREATE TABLE BOLETOS (
 ID_BOLETO INT AUTO_INCREMENT PRIMARY KEY,
 ID_MORADOR INT NOT NULL,
 VL_BOLETO DECIMAL(10,2) NOT NULL,
 DT_VENCIMENTO DATE NOT NULL,
 STATUS ENUM('ABERTO','PAGO','ATRASADO') DEFAULT 'ABERTO',
 FOREIGN KEY (ID_MORADOR) REFERENCES MORADORES(ID_MORADOR)
 );
 
 
 CREATE TABLE COMUNICADOS (
 ID_COMUNICADO INT AUTO_INCREMENT PRIMARY KEY,
 TITULO VARCHAR(100) NOT NULL,
 MENSAGEM TEXT NOT NULL,
 DT_COMUNICADO DATE NOT NULL,
 HR_COMUNICADO TIME,
 TIPO VARCHAR(30)
 );

 CREATE TABLE CONTRATOS (
 ID_CONTRATO INT AUTO_INCREMENT PRIMARY KEY,
 ID_FORNECEDOR INT NOT NULL,
 DESCRICAO TEXT,
 DATA_INICIO DATE,
 DATA_FIM DATE,
 VALOR DECIMAL(10,2),
 FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES(ID_FORNECEDOR)
 );

 CREATE TABLE CONTRATOS_RH (
 ID_CONTRATO_RH INT AUTO_INCREMENT PRIMARY KEY,
 ID_FUNCIONARIO INT NOT NULL,
 DESCRICAO TEXT,
 DATA_INICIO DATE,
 DATA_FIM DATE,
 SALARIO_ACORDADO DECIMAL(10,2),
 FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
 );
 
 CREATE TABLE VISITAS (
 ID_VISITA INT AUTO_INCREMENT PRIMARY KEY,
 ID_VISITANTE INT NOT NULL,
 ID_UNIDADE INT NOT NULL,
 ID_MORADOR_AUTORIZACAO INT NOT NULL,
 PLACA_VEICULO VARCHAR(10),
 DATA_ENTRADA DATETIME,
 DATA_SAIDA DATETIME,
 FOREIGN KEY (ID_VISITANTE) REFERENCES VISITANTES(ID_VISITANTE),
 FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADES(ID_UNIDADE),
 FOREIGN KEY (ID_MORADOR_AUTORIZACAO) REFERENCES MORADORES(ID_MORADOR)
 );

 CREATE TABLE CONTAS_PAGAR (
 ID_CONTA_PAGAR INT AUTO_INCREMENT PRIMARY KEY,
 ID_FORNECEDOR INT NOT NULL,
 DESCRICAO TEXT,
 VALOR DECIMAL(10,2),
 DATA_VENCIMENTO DATE,
 STATUS ENUM('ABERTO','PAGO','ATRASADO') DEFAULT 'ABERTO',
 FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES(ID_FORNECEDOR)
 );

 CREATE TABLE CONTAS_RECEBER (
 ID_CONTA_RECEBER INT AUTO_INCREMENT PRIMARY KEY,
 ID_MORADOR INT NOT NULL,
 DESCRICAO TEXT,
 VALOR DECIMAL(10,2),
 DATA_VENCIMENTO DATE,
 STATUS ENUM('ABERTO','PAGO','ATRASADO') DEFAULT 'ABERTO',
 FOREIGN KEY (ID_MORADOR) REFERENCES MORADORES(ID_MORADOR)
 );
 
 CREATE TABLE PAGAMENTOS (
 ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
 ID_CONTA_PAGAR INT NOT NULL,
 DATA_PAGAMENTO DATE,
 VALOR_PAGO DECIMAL(10,2),
 FORMA_PAGAMENTO VARCHAR(30),
 FOREIGN KEY (ID_CONTA_PAGAR) REFERENCES CONTAS_PAGAR(ID_CONTA_PAGAR)
 );

 CREATE TABLE RECEBIMENTOS (
 ID_RECEBIMENTO INT AUTO_INCREMENT PRIMARY KEY,
 ID_CONTA_RECEBER INT NOT NULL,
 DATA_RECEBIMENTO DATE,
 VALOR_RECEBIDO DECIMAL(10,2),
 FORMA_RECEBIMENTO VARCHAR(30),
 FOREIGN KEY (ID_CONTA_RECEBER) REFERENCES CONTAS_RECEBER(ID_CONTA_RECEBER)
 );

 CREATE TABLE CONTA_CORRENTE (
 ID_CONTA_CORRENTE INT AUTO_INCREMENT PRIMARY KEY,
 BANCO VARCHAR(50),
 AGENCIA VARCHAR(20),
 NUM_CONTA VARCHAR(20),
 SALDO_ATUAL DECIMAL(12,2)
 );

 CREATE TABLE MOV_CONTA_CORRENTE (
 ID_MOVIMENTO INT AUTO_INCREMENT PRIMARY KEY,
 ID_CONTA_CORRENTE INT NOT NULL,
 ID_CONTA INT,
 ORIGEM_CONTA ENUM('PAGAR','RECEBER'),
 TIPO_MOVIMENTO ENUM('CREDITO','DEBITO'),
 VALOR DECIMAL(10,2),
 DATA_MOVIMENTO DATE,
 HR_MOVIMENTO TIME,
 DESCRICAO TEXT,
 FOREIGN KEY (ID_CONTA_CORRENTE) REFERENCES CONTA_CORRENTE(ID_CONTA_CORRENTE)
 );




