CREATE DATABASE DBCONDOMINIOS;
USE DBCONDOMINIOS;
#DROP DATABASE DBCONDOMINIOS;
CREATE TABLE PESSOAS (
    ID_PESSOA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(55) NOT NULL,
    TIPO_PESSOA ENUM('FISICA', 'JURIDICA') NOT NULL,
    CPF_CNPJ VARCHAR(14) NOT NULL UNIQUE,
    DATA_CADASTRO DATE
);

CREATE TABLE CONTATOS (
    ID_CONTATO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PESSOA INT,
    TIPO_CONTATO VARCHAR(200),
    VALOR_CONTATO VARCHAR(200),
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS (ID_PESSOA)
);

CREATE TABLE ENDERECOS (
    ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PESSOA INT,
    LOGADOURO VARCHAR(200) NOT NULL,
    NUMERO INT,
    BAIRRO VARCHAR(50), -- Corrigido: BAIRRO
    CIDADE VARCHAR(50),
    UF CHAR(2),
    CEP CHAR(8) NOT NULL,
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS (ID_PESSOA)
);

CREATE TABLE UNIDADES (
    ID_UNIDADE INT PRIMARY KEY AUTO_INCREMENT,
    NUM_UNIDADE INT NOT NULL,
    BLOCO CHAR(3),
    TIPO VARCHAR(50),
    AREA_TOTAL DECIMAL(10,2) -- Alterado para DECIMAL para precisão
);

CREATE TABLE MORADORES (
    ID_MORADOR INT PRIMARY KEY AUTO_INCREMENT,
    ID_PESSOA INT,
    ID_UNIDADE INT,
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS (ID_PESSOA),
    FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADES (ID_UNIDADE)
);

CREATE TABLE FUNCIONARIOS (
    ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PESSOA INT,
    FUNCAO VARCHAR(100),
    DATA_ADMISSAO DATE,
    SALARIO DECIMAL(10,2),
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS (ID_PESSOA)
);

CREATE TABLE FORNECEDORES (
    ID_FORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
    ID_PESSOA INT,
    AREA_ATUACAO VARCHAR(200),
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS (ID_PESSOA)
);

CREATE TABLE VISITANTES (
    ID_VISITANTE INT PRIMARY KEY AUTO_INCREMENT, -- Corrigido: ID_VISITANTE
    ID_PESSOA INT,
    DOCUMENTO VARCHAR(14),
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS (ID_PESSOA)
);

CREATE TABLE AREA_COMUM (
    ID_AREA_COMUM INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(55),
    DESCRICAO_AREA VARCHAR(200),
    CAPACIDADE INT
);

CREATE TABLE RESERVAS (
    ID_RESERVA INT PRIMARY KEY AUTO_INCREMENT,
    ID_AREA_COMUM INT,
    ID_MORADOR INT,
    DATA_RESERVA DATE,
    HR_INICIO TIME,
    HR_FIM TIME,
    FOREIGN KEY (ID_AREA_COMUM) REFERENCES AREA_COMUM (ID_AREA_COMUM),
    FOREIGN KEY (ID_MORADOR) REFERENCES MORADORES (ID_MORADOR)
);

CREATE TABLE BOLETOS (
    ID_BOLETO INT PRIMARY KEY AUTO_INCREMENT,
    ID_MORADOR INT,
    VL_BOLETO DECIMAL(10,2),
    DT_VENCIMENTO DATE,
    BOLETO_STATUS ENUM ('PAGO', 'PENDENTE', 'ATRASADO', 'EXPIRADO'),
    FOREIGN KEY (ID_MORADOR) REFERENCES MORADORES (ID_MORADOR)
);

CREATE TABLE COMUNICADOS (
    ID_COMUNICADO INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(50),
    MENSAGEM VARCHAR(255),
    DT_COMUNICADO DATE,
    HR_COMUNICADO TIME,
    TIPO ENUM ('AVISO', 'COMUNICADO', 'NOTIFICAÇÃO', 'URGENTE')
);

CREATE TABLE CONTRATOS (
     ID_CONTRATO INT PRIMARY KEY AUTO_INCREMENT,
     ID_FORNECEDOR INT,
     DESCRICAO VARCHAR(255),
     DATA_INICIO DATE,
     DATA_FIM DATE,
     VALOR DECIMAL(10,2),
     FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES (ID_FORNECEDOR)
);

CREATE TABLE CONTRATOS_RH (
     ID_CONTRATO_RH INT PRIMARY KEY AUTO_INCREMENT,
     ID_FUNCIONARIO INT,
     DESCRICAO VARCHAR(255),
     DATA_INICIO DATE,
     DATA_FIM DATE,
     SALARIO_ACORDADO DECIMAL(10,2),
     FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO)
);

CREATE TABLE VISITAS (
     ID_VISITA INT PRIMARY KEY AUTO_INCREMENT,
     ID_VISITANTE INT,
     ID_UNIDADE INT,
     ID_MORADOR INT,
     PLACA_VEICULO VARCHAR(10),
     DATA_ENTRADA DATETIME, -- Alterado para DATETIME para compatibilidade geral
     DATA_SAIDA DATETIME,
     FOREIGN KEY (ID_VISITANTE) REFERENCES VISITANTES (ID_VISITANTE),
     FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADES (ID_UNIDADE),
     FOREIGN KEY (ID_MORADOR) REFERENCES MORADORES (ID_MORADOR)
);

CREATE TABLE CONTAS_PAGAR (
     ID_CONTA_PAGAR INT PRIMARY KEY AUTO_INCREMENT,
     ID_FORNECEDOR INT,
     DESCRICAO TEXT,
     VALOR DECIMAL(10,2),
     DATA_VENCIMENTO DATE,
     STATUS ENUM ('PAGO', 'PENDENTE', 'ATRASADO', 'EXPIRADO'),
     FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES (ID_FORNECEDOR)
);

CREATE TABLE CONTAS_RECEBER (
     ID_CONTA_RECEBER INT PRIMARY KEY AUTO_INCREMENT,
     ID_MORADOR INT,
     DESCRICAO TEXT,
     VALOR DECIMAL(10,2),
     DATA_VENCIMENTO DATE,
     STATUS ENUM ('PAGO', 'PENDENTE', 'ATRASADO', 'EXPIRADO'),
     FOREIGN KEY (ID_MORADOR) REFERENCES MORADORES (ID_MORADOR)
);

CREATE TABLE PAGAMENTOS (
     ID_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
     ID_CONTA_PAGAR INT,
     DATA_PAGAMENTO DATE,
     VALOR_PAGO DECIMAL(10,2),
     FORMA_PAGAMENTO VARCHAR(30),
     FOREIGN KEY (ID_CONTA_PAGAR) REFERENCES CONTAS_PAGAR (ID_CONTA_PAGAR)
);

CREATE TABLE RECEBIMENTOS (
     ID_RECEBIMENTO INT PRIMARY KEY AUTO_INCREMENT,
     ID_CONTA_RECEBER INT,
     DATA_RECEBIMENTO DATE,
     VALOR_RECEBIDO DECIMAL(10,2),
     FORMA_RECEBIMENTO VARCHAR(30),
     FOREIGN KEY (ID_CONTA_RECEBER) REFERENCES CONTAS_RECEBER (ID_CONTA_RECEBER)
);

CREATE TABLE CONTA_CORRENTE (
     ID_CONTA_CORRENTE INT PRIMARY KEY AUTO_INCREMENT,
     BANCO VARCHAR(50),
     AGENCIA VARCHAR(20),
     NUM_CONTA VARCHAR(20),
     SALDO_ATUAL DECIMAL(12,2)
);

CREATE TABLE MOV_CONTA_CORRENTE (
     ID_MOVIMENTO INT PRIMARY KEY AUTO_INCREMENT,
     ID_CONTA_CORRENTE INT,
     ID_CONTA INT, 
     ORIGEM_CONTA VARCHAR(20), 
     TIPO_MOVIMENTO VARCHAR(20), 
     VALOR DECIMAL(10,2),
     DATA_MOVIMENTO DATE,
     HR_MOVIMENTO TIME,
     DESCRICAO VARCHAR(255),
     FOREIGN KEY (ID_CONTA_CORRENTE) REFERENCES CONTA_CORRENTE (ID_CONTA_CORRENTE)
);